
CREATE TABLE account(
    id bigint PRIMARY KEY NOT NULL
);

CREATE TABLE transaction(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_from bigint REFERENCES account(id) NOT NULL,
    account_to bigint NOT NULL ,
    currency varchar(10) NOT NULL,
    sum double precision NOT NULL,
    sum_usd double precision NOT NULL,
    expense_category varchar(32) NOT NULL,
    datetime timestamp with time zone NOT NULL,
    limit_exceeded boolean NOT NULL
);




ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_ACCOUNT_FROM FOREIGN KEY (account_from) REFERENCES account (id);


CREATE TABLE month_limit(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id bigint REFERENCES account(id) ON DELETE CASCADE NOT NULL,
    limit_sum double precision default 0,
    datetime  timestamp with time zone,
    currency varchar(10)
);

CREATE TABLE currency_rates(
    currency varchar(10) PRIMARY KEY NOT NULL,
    rate double precision,
    datetime timestamp with time zone
);
INSERT INTO currency_rates (currency, rate, datetime) VALUES ('USD', 1, '2020-01-01 00:00:00.000000 +00:00');
